name: 'charity_data'

config-version: 2
version: '0.1'

profile: 'charity_duckdb'

model-paths: [ "models" ]
seed-paths: [ "seeds" ]
test-paths: [ "tests" ]
analysis-paths: [ "analysis" ]
macro-paths: [ "macros" ]

clean-targets:
  - "dbt_modules"
  - "logs"

models:
  charities:
    +materialized: view